- name: Create a ext4 filesystem on /dev/sdb
  become: true
  become_user: root
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sdb
    
- name: mount /mnt/data
  become: true
  become_user: root
  mount:
    path: /mnt/data
    src: /dev/sdb
    state: mounted
    fstype: ext4
    
- name: create linux user
  become: true
  become_user: root
  ansible.builtin.user:
    name: linux
    home : /mnt/data/home/linux
    shell: /bin/bash
    groups: users,sudo,admin,adm
    append: yes

- name: super user powers to linux
  become: true
  become_user: root
  copy:
    content: linux ALL=(ALL) NOPASSWD:ALL
    dest: /etc/sudoers.d/91-linux
    
- name: Set authorized key for linux@xpc
  become: true
  become_user: root
  ansible.posix.authorized_key:
    user: linux
    state: present
    manage_dir: yes
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA8/GphrIRwif4o2ZxHSYWyHMBIqCleYKQDKtlNjFJEId+auJJVL4cmJRGMFAIOo2ush7Ab8U8LxkdeIZUfwjRqlee2aSAhHsfK+YqNXOx6x9PREZu93YmACFbpkFw1ACq1CRotwfnffXySnmTSd2wKisG33911RFoDdNBmAWiOEIbAsSwpozNxehHr7HW4nPXDReQO6WBF4FIuOlLPM2iqNXa6yuMFExol8xDIQ4PDMt6oH4FiddECDHOF+wc6XDhdwiM26SKMqWB3577pJ62vUv6ip1xX+7IARJMxRkBVvZwmS3IEB40SUFDj++DHhBeYO9zOVrK245MAXqvjsuSYQ== linux@xpc"


- name: Set authorized key for mobaxterm@pcoam
  become: true
  become_user: root
  ansible.posix.authorized_key:
    user: linux
    state: present
    manage_dir: yes
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAq+4cfLij6BjRQvl0PKyUkSVa8c54/7+FSclRzwR1M4npKJ2a8XX6LAaZoIsrzoTmHfDLK2bZICcyHDx+ek8rDi22rO8Cz30FvI1KNztDABEsqu2otmF6oqiq3clrcOoDMgo2WZSibATzGCuNq1Xvt2Z/G6WEZ34zsdmbgnYMnZ3/M1iOwvbGNeTl7fPMCljreN5bUZPXOGLTndUjIcbel91aQ433v0RL7koZaQBJsG42xmutKkx6v0IuHimVLGmNLGsK57GLHjFP8dm4jv8YJuTAiy+0NIOS6iKFgpdror9+o2aaGzCi4zuvhnHf1M1h6ytdbPSU/YFSXKTr+dxbCw== mobaxterm@pcoam"


- name: Set authorized key for MainKeyPair
  become: true
  become_user: root
  ansible.posix.authorized_key:
    user: linux
    state: present
    manage_dir: yes
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOkQ/4I65lRavhUi5xsaJAgqAMEdw+DfRiPc/S9Gzddc MainKeyPair"