- name: timezone
  become: true
  become_user: root
  community.general.timezone:
    name: Europe/Paris

- name: Update and upgrade apt packages
  become: true
  become_user: root
  when: ansible_os_family == "Debian" 
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes
    cache_valid_time: 3600  # One day

- name: Update and upgrade packages on Fedora
  become: true
  become_user: root
  when: ansible_distribution == "Fedora"
  dnf:
    name: '*'
    state: latest
    update_cache: yes

- name: Install some modern packages
  become: true
  become_user: root
  when: ansible_os_family == "Debian" and ansible_distribution_major_version|int >= 22
  ansible.builtin.apt:
    pkg:
     - dnsutils

- name: Install some packages
  become: true
  become_user: root
  when: ansible_os_family == "Debian" and ansible_distribution_major_version|int < 22
  ansible.builtin.apt:
    pkg:
     - git
     - cron
     - netcat
     - vim


- name: Install some packages on Fedora
  become: true
  become_user: root
  when: ansible_distribution == "Fedora"
  dnf:
    name:
      - git
      - nc
      - vim
    state: present

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  become: true
  become_user: root
  reboot:
  when: reboot_required_file.stat.exists == true

- name: Add AAAA
  local_action: 
    module: amazon.aws.route53
    state: present
    zone: "{{ zonename }}"
    record: "{{ hostvars[inventory_hostname]['ansible_facts']['hostname'] }}.{{ publicdomainname }}"
    type: AAAA
    ttl: 300
    value: "{{ hostvars[inventory_hostname]['ansible_default_ipv6']['address'] }}"
    wait: true
    overwrite: true

- name: Remove old SSH key
  local_action: 
    module: command
    args:
      cmd: ssh-keygen -R {{ inventory_hostname }}
  delegate_to: localhost

- name: add new SSH key
  local_action: 
    module: command
    args:
      cmd:   ssh -o StrictHostKeyChecking=no -o BatchMode=yes {{ provisionninguser }}@{{ inventory_hostname }} ls 
  delegate_to: localhost
  ignore_errors: yes

