---

- name: This is a mad tester playbook
  hosts: all
  vars_files:
    - tf_ansible_global_vars_file.yml

  roles:
    - name: oam
      when: labels['role'] == 'oam'
    - name: persistedstorage
      when: labels['role'] == 'oam'