---

- name: This is a mad tester playbook
  hosts: all
  vars_files:
    - tf_ansible_global_vars_file.yml
    - only_ansible_global_vars_file.yml

  roles:
    - name: oam
    - name: persistedstorage
    - name: webserver
      become: true
      become_user: root
      when: labels['role'] == 'webserver'