apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash.fullname" . }}-config
data:
  logstash.conf: |
    input {
      tcp {
        port => 514
        type => "syslog"
      }
      udp {
        port => 514
        type => "syslog"
      }
    }

    filter {
      mutate {
        add_tag => [ "processed_by_node_${NODE_NAME}", "processed_by_pod_${POD_NAME}" ]
      }
    }

    output {
      elasticsearch {
        hosts => ["{{ .Values.elasticsearch.host }}"]
        user => "{{ .Values.elasticsearch.user }}"
        password => "${INGESTION_PASSWORD}"
        ssl => true
        cacert => "/etc/logstash/certificates/es-ca.crt"
        ssl_verification_mode => "full"
        index => "logstashonly-index-%{+YYYY.MM.dd}"
      }
    }
