---
- name: This is a mad tester playbook
  hosts: all
  vars_files:
    - tf_ansible_global_vars_file.yml
  tasks:
    - name: Create a flag file called '/var/tmp/yBO.ansibleflag'.
      become: true
      become_user: root
      copy:
        content: hello world from yBO
        dest: /var/tmp/yBO.ansibleflag

    - authorized_key:
        user: ec2-user
        state: present
        manage_dir: yes
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA8/GphrIRwif4o2ZxHSYWyHMBIqCleYKQDKtlNjFJEId+auJJVL4cmJRGMFAIOo2ush7Ab8U8LxkdeIZUfwjRqlee2aSAhHsfK+YqNXOx6x9PREZu93YmACFbpkFw1ACq1CRotwfnffXySnmTSd2wKisG33911RFoDdNBmAWiOEIbAsSwpozNxehHr7HW4nPXDReQO6WBF4FIuOlLPM2iqNXa6yuMFExol8xDIQ4PDMt6oH4FiddECDHOF+wc6XDhdwiM26SKMqWB3577pJ62vUv6ip1xX+7IARJMxRkBVvZwmS3IEB40SUFDj++DHhBeYO9zOVrK245MAXqvjsuSYQ== linux@xpc"

    - authorized_key:
        user: ec2-user
        state: present
        manage_dir: yes
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAq+4cfLij6BjRQvl0PKyUkSVa8c54/7+FSclRzwR1M4npKJ2a8XX6LAaZoIsrzoTmHfDLK2bZICcyHDx+ek8rDi22rO8Cz30FvI1KNztDABEsqu2otmF6oqiq3clrcOoDMgo2WZSibATzGCuNq1Xvt2Z/G6WEZ34zsdmbgnYMnZ3/M1iOwvbGNeTl7fPMCljreN5bUZPXOGLTndUjIcbel91aQ433v0RL7koZaQBJsG42xmutKkx6v0IuHimVLGmNLGsK57GLHjFP8dm4jv8YJuTAiy+0NIOS6iKFgpdror9+o2aaGzCi4zuvhnHf1M1h6ytdbPSU/YFSXKTr+dxbCw== mobaxterm@pcoam"

    - name: timezone
      become: true
      become_user: root
      community.general.timezone:
        name: Europe/Paris

    - name: Upgrade all packages
      become: true
      become_user: root
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Install a list of packages
      become: true
      become_user: root
      ansible.builtin.yum:
        name:
          - nmap-ncat
          - nmap
        state: present