apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: klustery-ca-bundle
spec:
  sources:
  - secret:
      name: klustery-root-ca-secret
      key: tls.crt
  target:
    # On distribue dans tous les namespaces pour que Traefik/Apps y aient accès
    namespaceSelector: {}
    secret:
      key: tls.ca
