- name: create demisto user
  ansible.builtin.user:
    name: demisto
    home : "{{ mnt_data_path }}/home/demisto"
    shell: /bin/bash
    groups: users,sudo,admin,adm
    append: yes

- name: super user powers to demisto
  copy:
    content: demisto ALL=(ALL) NOPASSWD:ALL
    dest: /etc/sudoers.d/91-demisto
    
- name: Set authorized key for demisto@xpc
  ansible.posix.authorized_key:
    user: demisto
    state: present
    manage_dir: yes
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA8/GphrIRwif4o2ZxHSYWyHMBIqCleYKQDKtlNjFJEId+auJJVL4cmJRGMFAIOo2ush7Ab8U8LxkdeIZUfwjRqlee2aSAhHsfK+YqNXOx6x9PREZu93YmACFbpkFw1ACq1CRotwfnffXySnmTSd2wKisG33911RFoDdNBmAWiOEIbAsSwpozNxehHr7HW4nPXDReQO6WBF4FIuOlLPM2iqNXa6yuMFExol8xDIQ4PDMt6oH4FiddECDHOF+wc6XDhdwiM26SKMqWB3577pJ62vUv6ip1xX+7IARJMxRkBVvZwmS3IEB40SUFDj++DHhBeYO9zOVrK245MAXqvjsuSYQ== demisto@xpc"


- name: Set authorized key for mobaxterm@pcoam
  ansible.posix.authorized_key:
    user: demisto
    state: present
    manage_dir: yes
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAq+4cfLij6BjRQvl0PKyUkSVa8c54/7+FSclRzwR1M4npKJ2a8XX6LAaZoIsrzoTmHfDLK2bZICcyHDx+ek8rDi22rO8Cz30FvI1KNztDABEsqu2otmF6oqiq3clrcOoDMgo2WZSibATzGCuNq1Xvt2Z/G6WEZ34zsdmbgnYMnZ3/M1iOwvbGNeTl7fPMCljreN5bUZPXOGLTndUjIcbel91aQ433v0RL7koZaQBJsG42xmutKkx6v0IuHimVLGmNLGsK57GLHjFP8dm4jv8YJuTAiy+0NIOS6iKFgpdror9+o2aaGzCi4zuvhnHf1M1h6ytdbPSU/YFSXKTr+dxbCw== mobaxterm@pcoam"

- name: Set authorized key for MainKeyPair
  ansible.posix.authorized_key:
    user: demisto
    state: present
    manage_dir: yes
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOkQ/4I65lRavhUi5xsaJAgqAMEdw+DfRiPc/S9Gzddc MainKeyPair"

- name: Install some packages 
  ansible.builtin.apt:
    pkg:
     - expect
     - jq
     - ncurses-bin
     - binutils
     - mlocate

- name: Ensure the var/lib/demisto directory structure exists
  file:
    path: "{{ mnt_data_path }}/var/lib/demisto"
    state: directory
    mode: '0755'

- name: bind mount /var/lib/demisto
  mount:
    path: "/var/lib/demisto"
    src: "{{ mnt_data_path }}/var/lib/demisto"
    opts: bind
    fstype: none
    state: mounted

- name: Ensure the usr/local/demisto directory structure exists
  file:
    path: "{{ mnt_data_path }}/usr/local/demisto"
    state: directory
    mode: '0755'

- name: bind mount /usr/local/demisto/
  mount:
    path: "/usr/local/demisto/"
    src: "{{ mnt_data_path }}/usr/local/demisto/"
    opts: bind
    fstype: none
    state: mounted

- name: Ensure the letsencrypt directory structure exists
  file:
    path: "{{ mnt_data_path }}/etc/letsencrypt"
    state: directory
    mode: '0755'

- name: bind mount {{ mnt_data_path }} /etc/letsencrypt
  become: true
  become_user: root
  mount:
    path: /etc/letsencrypt
    src: "{{ mnt_data_path }}/etc/letsencrypt"
    fstype: none
    opts: bind
    state: mounted
 
- name: Manage Let's Encrypt Certificates
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_create_if_missing: true
    certbot_certs:
      - email: "{{ webserver_certbot_email }}"
        domains:
          - "{{ webserver_host }}"
    certbot_auto_renew: true
    certbot_auto_renew_user: root
    certbot_auto_renew_hour: "0"
    certbot_auto_renew_minute: "0"
    certbot_auto_renew_options: "--quiet --no-self-upgrade"

- name: give ownership to demisto
  ansible.builtin.file:
    path: /etc/letsencrypt
    owner: demisto
    group: users
    mode: '0755'
    recurse: yes

- name: Ensure the install generated cert.key is removed before we create a symlink
  ansible.builtin.file:
    path: /usr/local/demisto/cert.key
    state: absent

- name: Create symbolic links to privkey.pem
  ansible.builtin.file:
    src: /etc/letsencrypt/live/{{ webserver_host }}/privkey.pem
    dest: /usr/local/demisto/cert.key
    owner: demisto
    group: users
    state: link

- name: Ensure the install generated cert.pem is removed before we create a symlink
  ansible.builtin.file:
    path: /usr/local/demisto/cert.pem
    state: absent

- name: Create symbolic links to fullchain.pem
  ansible.builtin.file:
    src: /etc/letsencrypt/live/{{ webserver_host }}/fullchain.pem
    dest: /usr/local/demisto/cert.pem
    owner: demisto
    group: users
    state: link

- name: install the xsoar 
  shell: /mnt/data/home/demisto/install.6.12.exp