resource "local_file" "tf_ansible_global_vars_file" {
  content  = <<-DOC
# Ansible vars_file containing variable values from Terraform.
# Generated by Terraform mgmt configuration.
publicdomainname : "${var.publicdomainname}"
zonename : "${data.aws_route53_zone.ybonnamyname.name}"
  DOC
  filename = "ansible/tf_ansible_global_vars_file.yml"
}


