apiVersion: v2
name: trust-manager-wrapper
description: A wrapper chart for trust-manager
type: application
version: 0.1.7
appVersion: "0.7.0"

dependencies:
  - name: trust-manager
    version: v0.7.0
    repository: https://charts.jetstack.io
